name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64

    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      # - name: Install dependencies
      #   run: |
      #     julia -e '
      #       using Pkg
      #       Pkg.add("PyCall")
      #       Pkg.add("SymPy")
      #       ENV["PYTHON"] = ""
      #       try
      #         Pkg.build("PyCall")
      #       catch e
      #         @warn "PyCall build failed, retrying..." exception=e
      #         sleep(5)
      #         Pkg.build("PyCall")
      #       end
      #       using PyCall
      #       pyimport_conda("sympy", "sympy")'
      - name: Install dependencies
        run: |
          julia -e '
            using Pkg
            Pkg.add("PyCall")
            Pkg.add("SymPy")
            ENV["PYTHON"] = Sys.iswindows() ? "python" : ""
            Pkg.build("PyCall")
            using PyCall
            pyimport_conda("sympy", "sympy")'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
